cities = {
    "Algiers": {"city": "Algiers",
                "province": "Algiers",
                "country": "Algeria",
                "continent": "Africa"},
    "Alexandria": {"city": "Alexandria",
                   "province": "Alexandria",
                   "country": "Egypt",
                   "continent": "Africa"},
    "Cairo-Egypt": {"city": "Cairo",
                    "province": "Cairo",
                    "country": "Egypt",
                    "continent": "Africa"},
    "Addis-Ababa": {"city": "Addis Ababa",
                    "province": "Oromia",
                    "country": "Ethiopia",
                    "continent": "Africa"},
    "Accra": {"city": "Accra",
              "province": "Greater Accra Region",
              "country": "Ghana",
              "continent": "Africa"},
    "Nairobi": {"city": "Nairobi",
                "province": "Nairobi City",
                "country": "Kenya",
                "continent": "Africa"},
    "Casablanca": {"city": "Casablanca",
                   "province": "Casablanca-Settat",
                   "country": "Morocco",
                   "continent": "Africa"},
    "Marrakech": {"city": "Marrakech",
                  "province": "Marrakesh-Safi",
                  "country": "Morocco",
                  "continent": "Africa"},
    "Rabat": {"city": "Rabat",
              "province": "Rabat-Salé-Kénitra",
              "country": "Morocco",
              "continent": "Africa"},
    "Lagos": {"city": "Lagos",
              "province": "Lagos",
              "country": "Nigeria",
              "continent": "Africa"},
    "Johannesburg": {"city": "Johannesburg",
                     "province": "Gauteng",
                     "country": "South Africa",
                     "continent": "Africa"},
    "Pretoria": {"city": "Pretoria",
                 "province": "Gauteng",
                 "country": "South Africa",
                 "continent": "Africa"},
    "Durban": {"city": "Durban",
               "province": "KwaZulu-Natal",
               "country": "South Africa",
               "continent": "Africa"},
    "Cape-Town": {"city": "Cape Town",
                  "province": "Western Cape",
                  "country": "South Africa",
                  "continent": "Africa"},
    "Dar-Es-Salaam": {"city": "Dar es Salaam",
                      "province": "Dar es Salaam",
                      "country": "Tanzania",
                      "continent": "Africa"},
    "Tunis": {"city": "Tunis",
              "province": "Tunis",
              "country": "Tunisia",
              "continent": "Africa"},
    "Kampala": {"city": "Kampala",
                "province": "Kampala",
                "country": "Uganda",
                "continent": "Africa"},
    "Harare": {"city": "Harare",
               "province": "Harare",
               "country": "Zimbabwe",
               "continent": "Africa"},
    "Yerevan": {"city": "Yerevan",
                "province": "Yerevan",
                "country": "Armenia",
                "continent": "Asia"},
    "Baku": {"city": "Baku",
             "province": "Baku",
             "country": "Azerbaijan",
             "continent": "Asia"},
    "Manama": {"city": "Manama",
               "province": "Manama",
               "country": "Bahrain",
               "continent": "Asia"},
    "Dhaka": {"city": "Dhaka",
              "province": "Dhaka District",
              "country": "Bangladesh",
              "continent": "Asia"},
    "Phnom-Penh": {"city": "Phnom Penh",
                   "province": "Phnom Penh",
                   "country": "Cambodia",
                   "continent": "Asia"},
    "Beijing": {"city": "Beijing",
                "province": "Beijing",
                "country": "China",
                "continent": "Asia"},
    "Guangzhou": {"city": "Guangzhou",
                  "province": "Guangdong",
                  "country": "China",
                  "continent": "Asia"},
    "Shenzhen": {"city": "Shenzhen",
                 "province": "Guangdong",
                 "country": "China",
                 "continent": "Asia"},
    "Hong-Kong": {"city": "Hong Kong",
                  "province": "Hong Kong",
                  "country": "China",
                  "continent": "Asia"},
    "Nanjing": {"city": "Nanjing",
                "province": "Jiangsu",
                "country": "China",
                "continent": "Asia"},
    "Suzhou": {"city": "Suzhou",
               "province": "Jiangsu",
               "country": "China",
               "continent": "Asia"},
    "Shanghai": {"city": "Shanghai",
                 "province": "Shanghai",
                 "country": "China",
                 "continent": "Asia"},
    "Chengdu": {"city": "Chengdu",
                "province": "Sichuan",
                "country": "China",
                "continent": "Asia"},
    "Hangzhou": {"city": "Hangzhou",
                 "province": "Zhejiang",
                 "country": "China",
                 "continent": "Asia"},
    "Batumi": {"city": "Batumi",
               "province": "Adjara",
               "country": "Georgia",
               "continent": "Asia"},
    "Tbilisi": {"city": "Tbilisi",
                "province": "Tbilisi",
                "country": "Georgia",
                "continent": "Asia"},
    "Delhi": {"city": "Delhi",
              "province": "Delhi",
              "country": "India",
              "continent": "Asia"},
    "Ahmedabad": {"city": "Ahmedabad",
                  "province": "Gujarat",
                  "country": "India",
                  "continent": "Asia"},
    "Surat": {"city": "Surat",
              "province": "Gujarat",
              "country": "India",
              "continent": "Asia"},
    "Gurgaon": {"city": "Gurgaon",
                "province": "Haryana",
                "country": "India",
                "continent": "Asia"},
    "Bangalore": {"city": "Bangalore",
                  "province": "Karnataka",
                  "country": "India",
                  "continent": "Asia"},
    "Kochi": {"city": "Kochi",
              "province": "Kerala",
              "country": "India",
              "continent": "Asia"},
    "Indore": {"city": "Indore",
               "province": "Madhya Pradesh",
               "country": "India",
               "continent": "Asia"},
    "Mumbai": {"city": "Mumbai",
               "province": "Maharashtra",
               "country": "India",
               "continent": "Asia"},
    "Pune": {"city": "Pune",
             "province": "Maharashtra",
             "country": "India",
             "continent": "Asia"},
    "Bhubaneswar": {"city": "Bhubaneswar",
                    "province": "Odisha",
                    "country": "India",
                    "continent": "Asia"},
    "Chandigarh": {"city": "Chandigarh",
                   "province": "Punjab",
                   "country": "India",
                   "continent": "Asia"},
    "Jaipur": {"city": "Jaipur",
               "province": "Rajasthan",
               "country": "India",
               "continent": "Asia"},
    "Chennai": {"city": "Chennai",
                "province": "Tamil Nadu",
                "country": "India",
                "continent": "Asia"},
    "Coimbatore": {"city": "Coimbatore",
                   "province": "Tamil Nadu",
                   "country": "India",
                   "continent": "Asia"},
    "Hyderabad": {"city": "Hyderabad",
                  "province": "Telangana",
                  "country": "India",
                  "continent": "Asia"},
    "Lucknow-Lakhnau": {"city": "Lucknow",
                        "province": "Uttar Pradesh",
                        "country": "India",
                        "continent": "Asia"},
    "Noida": {"city": "Noida",
              "province": "Uttar Pradesh",
              "country": "India",
              "continent": "Asia"},
    "Kolkata": {"city": "Kolkata",
                "province": "West Bengal",
                "country": "India",
                "continent": "Asia"},
    "Jakarta": {"city": "Jakarta",
                "province": "Jakarta",
                "country": "Indonesia",
                "continent": "Asia"},
    "Tehran": {"city": "Tehran",
               "province": "Tehran",
               "country": "Iran",
               "continent": "Asia"},
    "Baghdad": {"city": "Baghdad",
                "province": "Baghdad",
                "country": "Iraq",
                "continent": "Asia"},
    "Erbil-Irbil-Iraq": {"city": "Erbil",
                         "province": "Kurdistan",
                         "country": "Iraq",
                         "continent": "Asia"},
    "Haifa": {"city": "Haifa",
              "province": "Haifa",
              "country": "Israel",
              "continent": "Asia"},
    "Tel-Aviv-Yafo": {"city": "Tel Aviv-Yafo",
                      "province": "Tel Aviv-Yafo",
                      "country": "Israel",
                      "continent": "Asia"},
    "Tokyo": {"city": "Tokyo",
              "province": "Tokyo",
              "country": "Japan",
              "continent": "Asia"},
    "Amman": {"city": "Amman",
              "province": "Amman",
              "country": "Jordan",
              "continent": "Asia"},
    "Almaty": {"city": "Almaty",
               "province": "Almaty",
               "country": "Kazakhstan",
               "continent": "Asia"},
    "Astana-Nur-Sultan-Kazakhstan": {"city": "Astana",
                                     "province": "Astana",
                                     "country": "Kazakhstan",
                                     "continent": "Asia"},
    "Kuwait-City": {"city": "Kuwait City",
                    "province": "Kuwait City",
                    "country": "Kuwait",
                    "continent": "Asia"},
    "Bishkek": {"city": "Bishkek",
                "province": "Bishkek",
                "country": "Kyrgyzstan",
                "continent": "Asia"},
    "Beirut": {"city": "Beirut",
               "province": "Beirut",
               "country": "Lebanon",
               "continent": "Asia"},
    "Kuala-Lumpur": {"city": "Kuala Lumpur",
                     "province": "Kuala Lumpur",
                     "country": "Malaysia",
                     "continent": "Asia"},
    "Ulaanbaatar": {"city": "Ulaanbaatar",
                    "province": "Ulaanbaatar",
                    "country": "Mongolia",
                    "continent": "Asia"},
    "Kathmandu": {"city": "Kathmandu",
                  "province": "Bagmati",
                  "country": "Nepal",
                  "continent": "Asia"},
    "Muscat": {"city": "Muscat",
               "province": "Muscat",
               "country": "Oman",
               "continent": "Asia"},
    "Islamabad": {"city": "Islamabad",
                  "province": "Islamabad Capital Territory",
                  "country": "Pakistan",
                  "continent": "Asia"},
    "Lahore": {"city": "Lahore",
               "province": "Punjab",
               "country": "Pakistan",
               "continent": "Asia"},
    "Rawalpindi": {"city": "Rawalpindi",
                   "province": "Punjab",
                   "country": "Pakistan",
                   "continent": "Asia"},
    "Karachi": {"city": "Karachi",
                "province": "Sindh",
                "country": "Pakistan",
                "continent": "Asia"},
    "Jerusalem": {"city": "Jerusalem",
                  "province": "Jerusalem",
                  "country": "Palestine",
                  "continent": "Asia"},
    "Baguio": {"city": "Baguio",
               "province": "Benguet",
               "country": "Philippines",
               "continent": "Asia"},
    "Manila": {"city": "Manila",
               "province": "Manila",
               "country": "Philippines",
               "continent": "Asia"},
    "Doha": {"city": "Doha",
             "province": "Doha",
             "country": "Qatar",
             "continent": "Asia"},
    "Moscow": {"city": "Moscow",
               "province": "Moscow",
               "country": "Russia",
               "continent": "Asia"},
    "Nizhny-Novgorod-Russia": {"city": "Nizhny Novgorod",
                               "province": "Nizhny Novgorod",
                               "country": "Russia",
                               "continent": "Asia"},
    "Novosibirsk": {"city": "Novosibirsk",
                    "province": "Novosibirsk",
                    "country": "Russia",
                    "continent": "Asia"},
    "Saint-Petersburg": {"city": "Saint Petersburg",
                         "province": "Saint Petersburg",
                         "country": "Russia",
                         "continent": "Asia"},
    "Yekaterinburg": {"city": "Yekaterinburg",
                      "province": "Sverdlovsk",
                      "country": "Russia",
                      "continent": "Asia"},
    "Kazan": {"city": "Kazan",
              "province": "Tatarstan",
              "country": "Russia",
              "continent": "Asia"},
    "Jeddah-Jiddah": {"city": "Jeddah",
                      "province": "Mecca",
                      "country": "Saudi Arabia",
                      "continent": "Asia"},
    "Riyadh": {"city": "Riyadh",
               "province": "Riyadh",
               "country": "Saudi Arabia",
               "continent": "Asia"},
    "Singapore": {"city": "Singapore",
                  "province": "Singapore",
                  "country": "Singapore",
                  "continent": "Asia"},
    "Seoul": {"city": "Seoul",
              "province": "Seoul",
              "country": "South Korea",
              "continent": "Asia"},
    "Colombo": {"city": "Colombo",
                "province": "Western Province",
                "country": "Sri Lanka",
                "continent": "Asia"},
    "Taipei": {"city": "Taipei",
               "province": "Taipei",
               "country": "Taiwan",
               "continent": "Asia"},
    "Bangkok": {"city": "Bangkok",
                "province": "Bangkok",
                "country": "Thailand",
                "continent": "Asia"},
    "Chiang-Mai": {"city": "Chiang Mai",
                   "province": "Chiang Mai Province",
                   "country": "Thailand",
                   "continent": "Asia"},
    "Pattaya": {"city": "Pattaya",
                "province": "Chonburi",
                "country": "Thailand",
                "continent": "Asia"},
    "Abu-Dhabi": {"city": "Abu Dhabi",
                  "province": "Abu Dhabi",
                  "country": "United Arab Emirates",
                  "continent": "Asia"},
    "Dubai": {"city": "Dubai",
              "province": "Dubai",
              "country": "United Arab Emirates",
              "continent": "Asia"},
    "Sharjah": {"city": "Sharjah",
                "province": "Sharjah",
                "country": "United Arab Emirates",
                "continent": "Asia"},
    "Tashkent": {"city": "Tashkent",
                 "province": "Tashkent",
                 "country": "Uzbekistan",
                 "continent": "Asia"},
    "Hanoi": {"city": "Hanoi",
              "province": "Hanoi",
              "country": "Vietnam",
              "continent": "Asia"},
    "Ho-Chi-Minh-City": {"city": "Ho Chi Minh City",
                         "province": "Ho Chi Minh City",
                         "country": "Vietnam",
                         "continent": "Asia"},
    "Canberra": {"city": "Canberra",
                 "province": "Canberra",
                 "country": "Australia",
                 "continent": "Australia"},
    "Sydney": {"city": "Sydney",
               "province": "New South Wales",
               "country": "Australia",
               "continent": "Australia"},
    "Brisbane": {"city": "Brisbane",
                 "province": "Queensland",
                 "country": "Australia",
                 "continent": "Australia"},
    "Adelaide": {"city": "Adelaide",
                 "province": "South Australia",
                 "country": "Australia",
                 "continent": "Australia"},
    "Melbourne": {"city": "Melbourne",
                  "province": "Victoria",
                  "country": "Australia",
                  "continent": "Australia"},
    "Perth": {"city": "Perth",
              "province": "Western Australia",
              "country": "Australia",
              "continent": "Australia"},
    "Auckland": {"city": "Auckland",
                 "province": "Auckland",
                 "country": "New Zealand",
                 "continent": "Australia"},
    "Christchurch": {"city": "Christchurch",
                     "province": "Canterbury",
                     "country": "New Zealand",
                     "continent": "Australia"},
    "Wellington": {"city": "Wellington",
                   "province": "Wellington",
                   "country": "New Zealand",
                   "continent": "Australia"},
    "Tirana": {"city": "Tirana",
               "province": "Central Albania",
               "country": "Albania",
               "continent": "Europe"},
    "Graz": {"city": "Graz",
             "province": "Styria",
             "country": "Austria",
             "continent": "Europe"},
    "Vienna": {"city": "Vienna",
               "province": "Vienna",
               "country": "Austria",
               "continent": "Europe"},
    "Minsk": {"city": "Minsk",
              "province": "Minsk",
              "country": "Belarus",
              "continent": "Europe"},
    "Brussels": {"city": "Brussels",
                 "province": "Brussels",
                 "country": "Belgium",
                 "continent": "Europe"},
    "Antwerp": {"city": "Antwerp",
                "province": "Flanders",
                "country": "Belgium",
                "continent": "Europe"},
    "Sarajevo": {"city": "Sarajevo",
                 "province": "Sarajevo",
                 "country": "Bosnia and Herzegovina",
                 "continent": "Europe"},
    "Burgas": {"city": "Burgas",
               "province": "Burgas",
               "country": "Bulgaria",
               "continent": "Europe"},
    "Plovdiv": {"city": "Plovdiv",
                "province": "Plovdiv",
                "country": "Bulgaria",
                "continent": "Europe"},
    "Sofia": {"city": "Sofia",
              "province": "Sofia",
              "country": "Bulgaria",
              "continent": "Europe"},
    "Varna": {"city": "Varna",
              "province": "Varna",
              "country": "Bulgaria",
              "continent": "Europe"},
    "Split": {"city": "Split",
              "province": "Split-Dalmatia",
              "country": "Croatia",
              "continent": "Europe"},
    "Zagreb": {"city": "Zagreb",
               "province": "Zagreb",
               "country": "Croatia",
               "continent": "Europe"},
    "Limassol": {"city": "Limassol",
                 "province": "Limassol",
                 "country": "Cyprus",
                 "continent": "Europe"},
    "Nicosia": {"city": "Nicosia",
                "province": "Nicosia",
                "country": "Cyprus",
                "continent": "Europe"},
    "Plzen": {"city": "Plzen",
              "province": "Plzeň",
              "country": "Czech Republic",
              "continent": "Europe"},
    "Prague": {"city": "Prague",
               "province": "Prague",
               "country": "Czech Republic",
               "continent": "Europe"},
    "Brno": {"city": "Brno",
             "province": "South Moravian",
             "country": "Czech Republic",
             "continent": "Europe"},
    "Copenhagen": {"city": "Copenhagen",
                   "province": "Capital Region",
                   "country": "Denmark",
                   "continent": "Europe"},
    "Aarhus-Denmark": {"city": "Aarhus",
                       "province": "Central Denmark Region",
                       "country": "Denmark",
                       "continent": "Europe"},
    "Tallinn": {"city": "Tallinn",
                "province": "Harju",
                "country": "Estonia",
                "continent": "Europe"},
    "Tartu": {"city": "Tartu",
              "province": "Tartu",
              "country": "Estonia",
              "continent": "Europe"},
    "Tampere": {"city": "Tampere",
                "province": "Pirkanmaa",
                "country": "Finland",
                "continent": "Europe"},
    "Helsinki": {"city": "Helsinki",
                 "province": "Uusimaa",
                 "country": "Finland",
                 "continent": "Europe"},
    "Lyon": {"city": "Lyon",
             "province": "Auvergne-Rhône-Alpes",
             "country": "France",
             "continent": "Europe"},
    "Toulouse": {"city": "Toulouse",
                 "province": "Occitania",
                 "country": "France",
                 "continent": "Europe"},
    "Paris": {"city": "Paris",
              "province": "Île-de-France",
              "country": "France",
              "continent": "Europe"},
    "Freiburg-Im-Breisgau": {"city": "Freiburg im Breisgau",
                             "province": "Baden-Württemberg",
                             "country": "Germany",
                             "continent": "Europe"},
    "Heidelberg": {"city": "Heidelberg",
                   "province": "Baden-Württemberg",
                   "country": "Germany",
                   "continent": "Europe"},
    "Karlsruhe": {"city": "Karlsruhe",
                  "province": "Baden-Württemberg",
                  "country": "Germany",
                  "continent": "Europe"},
    "Mannheim": {"city": "Mannheim",
                 "province": "Baden-Württemberg",
                 "country": "Germany",
                 "continent": "Europe"},
    "Stuttgart": {"city": "Stuttgart",
                  "province": "Baden-Württemberg",
                  "country": "Germany",
                  "continent": "Europe"},
    "Munich": {"city": "Munich",
               "province": "Bavaria",
               "country": "Germany",
               "continent": "Europe"},
    "Nuremberg": {"city": "Nuremberg",
                  "province": "Bavaria",
                  "country": "Germany",
                  "continent": "Europe"},
    "Berlin": {"city": "Berlin",
               "province": "Berlin",
               "country": "Germany",
               "continent": "Europe"},
    "Bremen": {"city": "Bremen",
               "province": "Bremen",
               "country": "Germany",
               "continent": "Europe"},
    "Hamburg": {"city": "Hamburg",
                "province": "Hamburg",
                "country": "Germany",
                "continent": "Europe"},
    "Frankfurt": {"city": "Frankfurt",
                  "province": "Hesse",
                  "country": "Germany",
                  "continent": "Europe"},
    "Hanover": {"city": "Hanover",
                "province": "Lower Saxony",
                "country": "Germany",
                "continent": "Europe"},
    "Aachen": {"city": "Aachen",
               "province": "North Rhine-Westphalia",
               "country": "Germany",
               "continent": "Europe"},
    "Cologne": {"city": "Cologne",
                "province": "North Rhine-Westphalia",
                "country": "Germany",
                "continent": "Europe"},
    "Dusseldorf": {"city": "Dusseldorf",
                   "province": "North Rhine-Westphalia",
                   "country": "Germany",
                   "continent": "Europe"},
    "Essen": {"city": "Essen",
              "province": "North Rhine-Westphalia",
              "country": "Germany",
              "continent": "Europe"},
    "Dresden": {"city": "Dresden",
                "province": "Saxony",
                "country": "Germany",
                "continent": "Europe"},
    "Leipzig": {"city": "Leipzig",
                "province": "Saxony",
                "country": "Germany",
                "continent": "Europe"},
    "Athens": {"city": "Athens",
               "province": "Attica",
               "country": "Greece",
               "continent": "Europe"},
    "Thessaloniki": {"city": "Thessaloniki",
                     "province": "Macedonia",
                     "country": "Greece",
                     "continent": "Europe"},
    "Budapest": {"city": "Budapest",
                 "province": "Central Hungary",
                 "country": "Hungary",
                 "continent": "Europe"},
    "Reykjavik": {"city": "Reykjavik",
                  "province": "Capital Region",
                  "country": "Iceland",
                  "continent": "Europe"},
    "Galway": {"city": "Galway",
               "province": "Connacht",
               "country": "Ireland",
               "continent": "Europe"},
    "Dublin": {"city": "Dublin",
               "province": "Leinster",
               "country": "Ireland",
               "continent": "Europe"},
    "Cork": {"city": "Cork",
             "province": "Munster",
             "country": "Ireland",
             "continent": "Europe"},
    "Naples": {"city": "Naples",
               "province": "Campania",
               "country": "Italy",
               "continent": "Europe"},
    "Bologna": {"city": "Bologna",
                "province": "Emilia-Romagna",
                "country": "Italy",
                "continent": "Europe"},
    "Rome": {"city": "Rome",
             "province": "Lazio",
             "country": "Italy",
             "continent": "Europe"},
    "Milan": {"city": "Milan",
              "province": "Lombardy",
              "country": "Italy",
              "continent": "Europe"},
    "Turin": {"city": "Turin",
              "province": "Piedmont",
              "country": "Italy",
              "continent": "Europe"},
    "Cagliari": {"city": "Cagliari",
                 "province": "Sardinia",
                 "country": "Italy",
                 "continent": "Europe"},
    "Padova": {"city": "Padova",
               "province": "Veneto",
               "country": "Italy",
               "continent": "Europe"},
    "Verona": {"city": "Verona",
               "province": "Veneto",
               "country": "Italy",
               "continent": "Europe"},
    "Riga": {"city": "Riga",
             "province": "Riga",
             "country": "Latvia",
             "continent": "Europe"},
    "Vilnius": {"city": "Vilnius",
                "province": "Vilnius",
                "country": "Lithuania",
                "continent": "Europe"},
    "Luxembourg": {"city": "Luxembourg",
                   "province": "Luxembourg",
                   "country": "Luxembourg",
                   "continent": "Europe"},
    "Chisinau": {"city": "Chisinau",
                 "province": "Chisinau",
                 "country": "Moldova",
                 "continent": "Europe"},
    "Podgorica": {"city": "Podgorica",
                  "province": "Podgorica",
                  "country": "Montenegro",
                  "continent": "Europe"},
    "Groningen": {"city": "Groningen",
                  "province": "Groningen",
                  "country": "Netherlands",
                  "continent": "Europe"},
    "Maastricht": {"city": "Maastricht",
                   "province": "Limburg",
                   "country": "Netherlands",
                   "continent": "Europe"},
    "Eindhoven": {"city": "Eindhoven",
                  "province": "North Brabant",
                  "country": "Netherlands",
                  "continent": "Europe"},
    "Amsterdam": {"city": "Amsterdam",
                  "province": "North Holland",
                  "country": "Netherlands",
                  "continent": "Europe"},
    "Haarlem": {"city": "Haarlem",
                "province": "North Holland",
                "country": "Netherlands",
                "continent": "Europe"},
    "Rotterdam": {"city": "Rotterdam",
                  "province": "North Holland",
                  "country": "Netherlands",
                  "continent": "Europe"},
    "Delft": {"city": "Delft",
              "province": "South Holland",
              "country": "Netherlands",
              "continent": "Europe"},
    "The-Hague-Den-Haag-Netherlands": {"city": "The Hague",
                                       "province": "South Holland",
                                       "country": "Netherlands",
                                       "continent": "Europe"},
    "Utrecht": {"city": "Utrecht",
                "province": "Utrecht",
                "country": "Netherlands",
                "continent": "Europe"},
    "Skopje": {"city": "Skopje",
               "province": "Skopje",
               "country": "North Macedonia",
               "continent": "Europe"},
    "Oslo": {"city": "Oslo",
             "province": "Eastern Norway",
             "country": "Norway",
             "continent": "Europe"},
    "Trondheim": {"city": "Trondheim",
                  "province": "Trøndelag",
                  "country": "Norway",
                  "continent": "Europe"},
    "Bergen": {"city": "Bergen",
               "province": "Western Norway",
               "country": "Norway",
               "continent": "Europe"},
    "Poznan": {"city": "Poznan",
               "province": "Greater Poland",
               "country": "Poland",
               "continent": "Europe"},
    "Krakow-Cracow": {"city": "Krakow",
                      "province": "Lesser Poland",
                      "country": "Poland",
                      "continent": "Europe"},
    "Wroclaw": {"city": "Wroclaw",
                "province": "Lower Silesia",
                "country": "Poland",
                "continent": "Europe"},
    "Warsaw": {"city": "Warsaw",
               "province": "Masovian",
               "country": "Poland",
               "continent": "Europe"},
    "Gdansk": {"city": "Gdansk",
               "province": "Pomeranian",
               "country": "Poland",
               "continent": "Europe"},
    "Katowice": {"city": "Katowice",
                 "province": "Silesian",
                 "country": "Poland",
                 "continent": "Europe"},
    "Szczecin": {"city": "Szczecin",
                 "province": "West Pomeranian",
                 "country": "Poland",
                 "continent": "Europe"},
    "Lodz": {"city": "Lodz",
             "province": "Łódź",
             "country": "Poland",
             "continent": "Europe"},
    "Lisbon": {"city": "Lisbon",
               "province": "Lisbon",
               "country": "Portugal",
               "continent": "Europe"},
    "Braga": {"city": "Braga",
              "province": "Norte",
              "country": "Portugal",
              "continent": "Europe"},
    "Porto": {"city": "Porto",
              "province": "Norte",
              "country": "Portugal",
              "continent": "Europe"},
    "Oradea": {"city": "Oradea",
               "province": "Bihor County",
               "country": "Romania",
               "continent": "Europe"},
    "Brasov": {"city": "Brasov",
               "province": "Brașov",
               "country": "Romania",
               "continent": "Europe"},
    "Bucharest": {"city": "Bucharest",
                  "province": "Bucharest",
                  "country": "Romania",
                  "continent": "Europe"},
    "Cluj-napoca": {"city": "Cluj-Napoca",
                    "province": "Cluj County",
                    "country": "Romania",
                    "continent": "Europe"},
    "Constanta": {"city": "Constanta",
                  "province": "Constanța",
                  "country": "Romania",
                  "continent": "Europe"},
    "Iasi": {"city": "Iasi",
             "province": "Iași",
             "country": "Romania",
             "continent": "Europe"},
    "Sibiu": {"city": "Sibiu",
              "province": "Sibiu",
              "country": "Romania",
              "continent": "Europe"},
    "Timisoara": {"city": "Timisoara",
                  "province": "Timiș",
                  "country": "Romania",
                  "continent": "Europe"},
    "Belgrade": {"city": "Belgrade",
                 "province": "Belgrade",
                 "country": "Serbia",
                 "continent": "Europe"},
    "Nis": {"city": "Nis",
            "province": "Nišava",
            "country": "Serbia",
            "continent": "Europe"},
    "Pristina": {"city": "Pristina",
                 "province": "Pristina",
                 "country": "Serbia",
                 "continent": "Europe"},
    "Novi-Sad": {"city": "Novi Sad",
                 "province": "Vojvodina",
                 "country": "Serbia",
                 "continent": "Europe"},
    "Bratislava": {"city": "Bratislava",
                   "province": "Bratislava",
                   "country": "Slovakia",
                   "continent": "Europe"},
    "Ljubljana": {"city": "Ljubljana",
                  "province": "Central Slovenia",
                  "country": "Slovenia",
                  "continent": "Europe"},
    "Malaga": {"city": "Malaga",
               "province": "Andalusia",
               "country": "Spain",
               "continent": "Europe"},
    "Sevilla": {"city": "Sevilla",
                "province": "Andalusia",
                "country": "Spain",
                "continent": "Europe"},
    "Bilbao": {"city": "Bilbao",
               "province": "Basque Country",
               "country": "Spain",
               "continent": "Europe"},
    "Barcelona": {"city": "Barcelona",
                  "province": "Catalonia",
                  "country": "Spain",
                  "continent": "Europe"},
    "Madrid": {"city": "Madrid",
               "province": "Community of Madrid",
               "country": "Spain",
               "continent": "Europe"},
    "Valencia": {"city": "Valencia",
                 "province": "Valencia",
                 "country": "Spain",
                 "continent": "Europe"},
    "Lund": {"city": "Lund",
             "province": "Scania",
             "country": "Sweden",
             "continent": "Europe"},
    "Malmo": {"city": "Malmo",
              "province": "Scania",
              "country": "Sweden",
              "continent": "Europe"},
    "Stockholm": {"city": "Stockholm",
                  "province": "Södermanland",
                  "country": "Sweden",
                  "continent": "Europe"},
    "Gothenburg": {"city": "Gothenburg",
                   "province": "Västergötland",
                   "country": "Sweden",
                   "continent": "Europe"},
    "Basel": {"city": "Basel",
              "province": "Basel-Stadt",
              "country": "Switzerland",
              "continent": "Europe"},
    "Bern": {"city": "Bern",
             "province": "Bern",
             "country": "Switzerland",
             "continent": "Europe"},
    "Geneva": {"city": "Geneva",
               "province": "Geneva",
               "country": "Switzerland",
               "continent": "Europe"},
    "Lausanne": {"city": "Lausanne",
                 "province": "Vaud",
                 "country": "Switzerland",
                 "continent": "Europe"},
    "Zurich": {"city": "Zurich",
               "province": "Zurich",
               "country": "Switzerland",
               "continent": "Europe"},
    "Izmir": {"city": "Izmir",
              "province": "Aegean",
              "country": "Turkey",
              "continent": "Europe"},
    "Ankara": {"city": "Ankara",
               "province": "Central Anatolia",
               "country": "Turkey",
               "continent": "Europe"},
    "Istanbul": {"city": "Istanbul",
                 "province": "Marmara",
                 "country": "Turkey",
                 "continent": "Europe"},
    "Dnipropetrovsk": {"city": "Dnipropetrovsk",
                       "province": "Dnipropetrovsk",
                       "country": "Ukraine",
                       "continent": "Europe"},
    "Kharkiv": {"city": "Kharkiv",
                "province": "Kharkiv",
                "country": "Ukraine",
                "continent": "Europe"},
    "Kiev": {"city": "Kiev",
             "province": "Kiev",
             "country": "Ukraine",
             "continent": "Europe"},
    "Lviv": {"city": "Lviv",
             "province": "Lviv",
             "country": "Ukraine",
             "continent": "Europe"},
    "Odesa": {"city": "Odesa",
              "province": "Odesa",
              "country": "Ukraine",
              "continent": "Europe"},
    "Aberdeen": {"city": "Aberdeen",
                 "province": "Aberdeen City",
                 "country": "United Kingdom",
                 "continent": "Europe"},
    "Edinburgh": {"city": "Edinburgh",
                  "province": "City of Edinburgh",
                  "country": "United Kingdom",
                  "continent": "Europe"},
    "Glasgow": {"city": "Glasgow",
                "province": "Glasgow City",
                "country": "United Kingdom",
                "continent": "Europe"},
    "London": {"city": "London",
               "province": "London",
               "country": "United Kingdom",
               "continent": "Europe"},
    "Newcastle-Upon-Tyne": {"city": "Newcastle upon Tyne",
                            "province": "North East England",
                            "country": "United Kingdom",
                            "continent": "Europe"},
    "Liverpool": {"city": "Liverpool",
                  "province": "North West England",
                  "country": "United Kingdom",
                  "continent": "Europe"},
    "Manchester": {"city": "Manchester",
                   "province": "North West England",
                   "country": "United Kingdom",
                   "continent": "Europe"},
    "Brighton": {"city": "Brighton",
                 "province": "South East England",
                 "country": "United Kingdom",
                 "continent": "Europe"},
    "Birmingham": {"city": "Birmingham",
                   "province": "West Midlands",
                   "country": "United Kingdom",
                   "continent": "Europe"},
    "Sheffield": {"city": "Sheffield",
                  "province": "Yorkshire and the Humber",
                  "country": "United Kingdom",
                  "continent": "Europe"},
    "Calgary": {"city": "Calgary",
                "province": "Alberta",
                "country": "Canada",
                "continent": "North America"},
    "Edmonton": {"city": "Edmonton",
                 "province": "Alberta",
                 "country": "Canada",
                 "continent": "North America"},
    "Kelowna": {"city": "Kelowna",
                "province": "British Columbia",
                "country": "Canada",
                "continent": "North America"},
    "Surrey": {"city": "Surrey",
               "province": "British Columbia",
               "country": "Canada",
               "continent": "North America"},
    "Vancouver": {"city": "Vancouver",
                  "province": "British Columbia",
                  "country": "Canada",
                  "continent": "North America"},
    "Victoria": {"city": "Victoria",
                 "province": "British Columbia",
                 "country": "Canada",
                 "continent": "North America"},
    "Winnipeg": {"city": "Winnipeg",
                 "province": "Manitoba",
                 "country": "Canada",
                 "continent": "North America"},
    "Halifax": {"city": "Halifax",
                "province": "Nova Scotia",
                "country": "Canada",
                "continent": "North America"},
    "Hamilton": {"city": "Hamilton",
                 "province": "Ontario",
                 "country": "Canada",
                 "continent": "North America"},
    "London-Canada": {"city": "London",
                      "province": "Ontario",
                      "country": "Canada",
                      "continent": "North America"},
    "Mississauga": {"city": "Mississauga",
                    "province": "Ontario",
                    "country": "Canada",
                    "continent": "North America"},
    "Ottawa": {"city": "Ottawa",
               "province": "Ontario",
               "country": "Canada",
               "continent": "North America"},
    "Toronto": {"city": "Toronto",
                "province": "Ontario",
                "country": "Canada",
                "continent": "North America"},
    "Montreal": {"city": "Montreal",
                 "province": "Quebec",
                 "country": "Canada",
                 "continent": "North America"},
    "Quebec-City": {"city": "Québec City",
                    "province": "Quebec",
                    "country": "Canada",
                    "continent": "North America"},
    "Regina": {"city": "Regina",
               "province": "Saskatchewan",
               "country": "Canada",
               "continent": "North America"},
    "Saskatoon": {"city": "Saskatoon",
                  "province": "Saskatchewan",
                  "country": "Canada",
                  "continent": "North America"},
    "San-Jose-Costa-Rica": {"city": "San José",
                            "province": "Province of San José",
                            "country": "Costa Rica",
                            "continent": "North America"},
    "Guatemala-City": {"city": "Guatemala City",
                       "province": "Guatemala Department",
                       "country": "Guatemala",
                       "continent": "North America"},
    "Guadalajara": {"city": "Guadalajara",
                    "province": "Jalisco",
                    "country": "Mexico",
                    "continent": "North America"},
    "Mexico-City": {"city": "Mexico City",
                    "province": "Mexico City",
                    "country": "Mexico",
                    "continent": "North America"},
    "Monterrey": {"city": "Monterrey",
                  "province": "Nuevo León",
                  "country": "Mexico",
                  "continent": "North America"},
    "Queretaro-Santiago-de-Queretaro-Mexico": {"city": "Santiago de Querétaro",
                                               "province": "Querétaro",
                                               "country": "Mexico",
                                               "continent": "North America"},
    "Cancun": {"city": "Cancun",
               "province": "Quintana Roo",
               "country": "Mexico",
               "continent": "North America"},
    "Merida": {"city": "Merida",
               "province": "Yucatán",
               "country": "Mexico",
               "continent": "North America"},
    "Panama-City": {"city": "Panama City",
                    "province": "Panamá Province",
                    "country": "Panama",
                    "continent": "North America"},
    "Phoenix": {"city": "Phoenix",
                "province": "Arizona",
                "country": "United States",
                "continent": "North America"},
    "Tucson": {"city": "Tucson",
               "province": "Arizona",
               "country": "United States",
               "continent": "North America"},
    "Los-Angeles": {"city": "Los Angeles",
                    "province": "California",
                    "country": "United States",
                    "continent": "North America"},
    "Sacramento": {"city": "Sacramento",
                   "province": "California",
                   "country": "United States",
                   "continent": "North America"},
    "San-Diego": {"city": "San Diego",
                  "province": "California",
                  "country": "United States",
                  "continent": "North America"},
    "San-Francisco": {"city": "San Francisco",
                      "province": "California",
                      "country": "United States",
                      "continent": "North America"},
    "San-Jose": {"city": "San Jose",
                 "province": "California",
                 "country": "United States",
                 "continent": "North America"},
    "Denver": {"city": "Denver",
               "province": "Colorado",
               "country": "United States",
               "continent": "North America"},
    "Jacksonville": {"city": "Jacksonville",
                     "province": "Florida",
                     "country": "United States",
                     "continent": "North America"},
    "Miami": {"city": "Miami",
              "province": "Florida",
              "country": "United States",
              "continent": "North America"},
    "Orlando": {"city": "Orlando",
                "province": "Florida",
                "country": "United States",
                "continent": "North America"},
    "Tampa": {"city": "Tampa",
              "province": "Florida",
              "country": "United States",
              "continent": "North America"},
    "Atlanta": {"city": "Atlanta",
                "province": "Georgia",
                "country": "United States",
                "continent": "North America"},
    "Honolulu": {"city": "Honolulu",
                 "province": "Hawaii",
                 "country": "United States",
                 "continent": "North America"},
    "Chicago": {"city": "Chicago",
                "province": "Illinois",
                "country": "United States",
                "continent": "North America"},
    "Indianapolis": {"city": "Indianapolis",
                     "province": "Indiana",
                     "country": "United States",
                     "continent": "North America"},
    "New-Orleans": {"city": "New Orleans",
                    "province": "Louisiana",
                    "country": "United States",
                    "continent": "North America"},
    "Baltimore": {"city": "Baltimore",
                  "province": "Maryland",
                  "country": "United States",
                  "continent": "North America"},
    "Boston": {"city": "Boston",
               "province": "Massachusetts",
               "country": "United States",
               "continent": "North America"},
    "Minneapolis": {"city": "Minneapolis",
                    "province": "Minnesota",
                    "country": "United States",
                    "continent": "North America"},
    "Saint-Louis": {"city": "Saint Louis",
                    "province": "Missouri",
                    "country": "United States",
                    "continent": "North America"},
    "Las-Vegas": {"city": "Las Vegas",
                  "province": "Nevada",
                  "country": "United States",
                  "continent": "North America"},
    "Albuquerque": {"city": "Albuquerque",
                    "province": "New Mexico",
                    "country": "United States",
                    "continent": "North America"},
    "New-York": {"city": "New York",
                 "province": "New York",
                 "country": "United States",
                 "continent": "North America"},
    "Raleigh": {"city": "Raleigh",
                "province": "North Carolina",
                "country": "United States",
                "continent": "North America"},
    "Cincinnati": {"city": "Cincinnati",
                   "province": "Ohio",
                   "country": "United States",
                   "continent": "North America"},
    "Columbus": {"city": "Columbus",
                 "province": "Ohio",
                 "country": "United States",
                 "continent": "North America"},
    "Portland": {"city": "Portland",
                 "province": "Oregon",
                 "country": "United States",
                 "continent": "North America"},
    "Philadelphia": {"city": "Philadelphia",
                     "province": "Pennsylvania",
                     "country": "United States",
                     "continent": "North America"},
    "Nashville": {"city": "Nashville",
                  "province": "Tennessee",
                  "country": "United States",
                  "continent": "North America"},
    "Austin": {"city": "Austin",
               "province": "Texas",
               "country": "United States",
               "continent": "North America"},
    "Dallas": {"city": "Dallas",
               "province": "Texas",
               "country": "United States",
               "continent": "North America"},
    "Houston": {"city": "Houston",
                "province": "Texas",
                "country": "United States",
                "continent": "North America"},
    "San-Antonio": {"city": "San Antonio",
                    "province": "Texas",
                    "country": "United States",
                    "continent": "North America"},
    "Salt-Lake-City": {"city": "Salt Lake City",
                       "province": "Utah",
                       "country": "United States",
                       "continent": "North America"},
    "Seattle": {"city": "Seattle",
                "province": "Washington",
                "country": "United States",
                "continent": "North America"},
    "Spokane": {"city": "Spokane",
                "province": "Washington",
                "country": "United States",
                "continent": "North America"},
    "Washington": {"city": "Washington",
                   "province": "Washington",
                   "country": "United States",
                   "continent": "North America"},
    "Madison": {"city": "Madison",
                "province": "Wisconsin",
                "country": "United States",
                "continent": "North America"},
    "Buenos-Aires": {"city": "Buenos Aires",
                     "province": "Buenos Aires",
                     "country": "Argentina",
                     "continent": "South America"},
    "Cordoba": {"city": "Cordoba",
                "province": "Cordoba",
                "country": "Argentina",
                "continent": "South America"},
    "Brasilia": {"city": "Brasilia",
                 "province": "Federal District",
                 "country": "Brazil",
                 "continent": "South America"},
    "Belo-Horizonte": {"city": "Belo Horizonte",
                       "province": "Minas Gerais",
                       "country": "Brazil",
                       "continent": "South America"},
    "Curitiba": {"city": "Curitiba",
                 "province": "Paraná",
                 "country": "Brazil",
                 "continent": "South America"},
    "Recife": {"city": "Recife",
               "province": "Pernambuco",
               "country": "Brazil",
               "continent": "South America"},
    "Porto-Alegre": {"city": "Porto Alegre",
                     "province": "Rio Grande do Sul",
                     "country": "Brazil",
                     "continent": "South America"},
    "Rio-De-Janeiro": {"city": "Rio de Janeiro",
                       "province": "Rio de Janeiro",
                       "country": "Brazil",
                       "continent": "South America"},
    "Florianopolis": {"city": "Florianopolis",
                      "province": "Santa Catarina",
                      "country": "Brazil",
                      "continent": "South America"},
    "Campinas": {"city": "Campinas",
                 "province": "São Paulo",
                 "country": "Brazil",
                 "continent": "South America"},
    "Sao-Paulo": {"city": "Sao Paulo",
                  "province": "São Paulo",
                  "country": "Brazil",
                  "continent": "South America"},
    "Santiago": {"city": "Santiago",
                 "province": "Santiago Metropolitan Region",
                 "country": "Chile",
                 "continent": "South America"},
    "Medellin": {"city": "Medellin",
                 "province": "Aburrá Valley",
                 "country": "Colombia",
                 "continent": "South America"},
    "Bogota": {"city": "Bogota",
               "province": "Capital District",
               "country": "Colombia",
               "continent": "South America"},
    "Cali": {"city": "Cali",
             "province": "Valle del Cauca",
             "country": "Colombia",
             "continent": "South America"},
    "Cuenca": {"city": "Cuenca",
               "province": "Azuay",
               "country": "Ecuador",
               "continent": "South America"},
    "Quito": {"city": "Quito",
              "province": "Pichincha",
              "country": "Ecuador",
              "continent": "South America"},
    "Asuncion": {"city": "Asuncion",
                 "province": "Asuncion",
                 "country": "Paraguay",
                 "continent": "South America"},
    "Lima": {"city": "Lima",
             "province": "Lima",
             "country": "Peru",
             "continent": "South America"},
    "Port-Of-Spain": {"city": "Port of Spain",
                      "province": "Port of Spain",
                      "country": "Trinidad and Tobago",
                      "continent": "South America"},
    "Montevideo": {"city": "Montevideo",
                   "province": "Montevideo",
                   "country": "Uruguay",
                   "continent": "South America"}
}
