-- cost_of_living.sql

CREATE TABLE IF NOT EXISTS cost_of_living (
--    id SERIAL PRIMARY KEY,
    today DATE,
    city VARCHAR(100),
    province VARCHAR(100),
    country VARCHAR(100),
    continent VARCHAR(100),

    meal__inexpensive_restaurant DECIMAL(10,2),
    meal__inexpensive_restaurant_pr VARCHAR(50),
    meal_for_2_people__mid_range_restaurant__three_course DECIMAL(10,2),
    meal_for_2_people__mid_range_restaurant__three_course_pr VARCHAR(50),
    mcmeal_at_mcdonalds_or_equivalent_combo_meal DECIMAL(10,2),
    mcmeal_at_mcdonalds_or_equivalent_combo_meal_pr VARCHAR(50),

    domestic_beer_0_5_liter_draught DECIMAL(10,2),
    domestic_beer_0_5_liter_draught_pr VARCHAR(50),
    imported_beer_0_33_liter_bottle DECIMAL(10,2),
    imported_beer_0_33_liter_bottle_pr VARCHAR(50),
    cappuccino_regular DECIMAL(10,2),
    cappuccino_regular_pr VARCHAR(50),
    cokepepsi_0_33_liter_bottle DECIMAL(10,2),
    cokepepsi_0_33_liter_bottle_pr VARCHAR(50),
    water_0_33_liter_bottle DECIMAL(10,2),
    water_0_33_liter_bottle_pr VARCHAR(50),

    milk_regular__1_liter DECIMAL(10,2),
    milk_regular__1_liter_pr VARCHAR(50),
    loaf_of_fresh_white_bread_500g DECIMAL(10,2),
    loaf_of_fresh_white_bread_500g_pr VARCHAR(50),
    rice_white__1kg DECIMAL(10,2),
    rice_white__1kg_pr VARCHAR(50),
    eggs_regular_12 DECIMAL(10,2),
    eggs_regular_12_pr VARCHAR(50),
    local_cheese_1kg DECIMAL(10,2),
    local_cheese_1kg_pr VARCHAR(50),
    chicken_fillets_1kg DECIMAL(10,2),
    chicken_fillets_1kg_pr VARCHAR(50),
    buffalo_round_1kg_or_equivalent_back_leg_red_meat DECIMAL(10,2),
    buffalo_round_1kg_or_equivalent_back_leg_red_meat_pr VARCHAR(50),

    apples_1kg DECIMAL(10,2),
    apples_1kg_pr VARCHAR(50),
    banana_1kg DECIMAL(10,2),
    banana_1kg_pr VARCHAR(50),
    oranges_1kg DECIMAL(10,2),
    oranges_1kg_pr VARCHAR(50),
    tomato_1kg DECIMAL(10,2),
    tomato_1kg_pr VARCHAR(50),
    potato_1kg DECIMAL(10,2),
    potato_1kg_pr VARCHAR(50),
    onion_1kg DECIMAL(10,2),
    onion_1kg_pr VARCHAR(50),
    lettuce_1_head DECIMAL(10,2),
    lettuce_1_head_pr VARCHAR(50),
    water_1_5_liter_bottle DECIMAL(10,2),
    water_1_5_liter_bottle_pr VARCHAR(50),

    bottle_of_wine_mid_range DECIMAL(10,2),
    bottle_of_wine_mid_range_pr VARCHAR(50),
    domestic_beer_0_5_liter_bottle DECIMAL(10,2),
    domestic_beer_0_5_liter_bottle_pr VARCHAR(50),
    cigarettes_20_pack_marlboro DECIMAL(10,2),
    cigarettes_20_pack_marlboro_pr VARCHAR(50),

    one_way_ticket_local_transport DECIMAL(10,2),
    one_way_ticket_local_transport_pr VARCHAR(50),
    monthly_pass_regular_price DECIMAL(10,2),
    monthly_pass_regular_price_pr VARCHAR(50),
    taxi_start_normal_tariff DECIMAL(10,2),
    taxi_start_normal_tariff_pr VARCHAR(50),
    taxi_1km_normal_tariff DECIMAL(10,2),
    taxi_1km_normal_tariff_pr VARCHAR(50),
    taxi_1hour_waiting_normal_tariff DECIMAL(10,2),
    taxi_1hour_waiting_normal_tariff_pr VARCHAR(50),

    gasoline_1_liter DECIMAL(10,2),
    gasoline_1_liter_pr VARCHAR(50),
    volkswagen_golf_1_4_90_kw_trendline_or_equivalent_new_car DECIMAL(10,2),
    volkswagen_golf_1_4_90_kw_trendline_or_equivalent_new_car_pr VARCHAR(100),
    toyota_corolla_sedan_1_6l_97kw_comfort_or_equivalent_new_car DECIMAL(10,2),
    toyota_corolla_sedan_1_6l_97kw_comfort_or_equivalent_new_car_pr VARCHAR(100),

    basic_electricity__heating__cooling__water__garbage_for_85m2_apartment DECIMAL(10,2),
    basic_electricity__heating__cooling__water__garbage_for_85m2_apartment_pr VARCHAR(50),
    mobile_phone_monthly_plan_with_calls_and_10gb_plus_data DECIMAL(10,2),
    mobile_phone_monthly_plan_with_calls_and_10gb_plus_data_pr VARCHAR(50),
    internet_60_mbps_or_more__unlimited_data__cableadsl DECIMAL(10,2),
    internet_60_mbps_or_more__unlimited_data__cableadsl_pr VARCHAR(50),
    fitness_club__monthly_fee_for_1_adult DECIMAL(10,2),
    fitness_club__monthly_fee_for_1_adult_pr VARCHAR(50),
    tennis_court_rent_1_hour_on_weekend DECIMAL(10,2),
    tennis_court_rent_1_hour_on_weekend_pr VARCHAR(50),
    cinema__international_release__1_seat DECIMAL(10,2),
    cinema__international_release__1_seat_pr VARCHAR(50),

    preschool_or_kindergarten__full_day__private__monthly_for_1_child DECIMAL(10,2),
    preschool_or_kindergarten__full_day__private__monthly_for_1_child_pr VARCHAR(50),
    international_primary_school__yearly_for_1_child DECIMAL(10,2),
    international_primary_school__yearly_for_1_child_pr VARCHAR(100),

    one_pair_of_jeans_levis_501_or_similar DECIMAL(10,2),
    one_pair_of_jeans_levis_501_or_similar_pr VARCHAR(50),
    one_summer_dress_in_a_chain_store_zara_hnm DECIMAL(10,2),
    one_summer_dress_in_a_chain_store_zara_hnm_pr VARCHAR(50),
    one_pair_of_nike_running_shoes_mid_range DECIMAL(10,2),
    one_pair_of_nike_running_shoes_mid_range_pr VARCHAR(50),
    one_pair_of_men_leather_business_shoes DECIMAL(10,2),
    one_pair_of_men_leather_business_shoes_pr VARCHAR(50),

    apartment_1_bedroom_in_city_centre DECIMAL(10,2),
    apartment_1_bedroom_in_city_centre_pr VARCHAR(100),
    apartment_1_bedroom_outside_of_centre DECIMAL(10,2),
    apartment_1_bedroom_outside_of_centre_pr VARCHAR(100),
    apartment_3_bedrooms_in_city_centre DECIMAL(10,2),
    apartment_3_bedrooms_in_city_centre_pr VARCHAR(100),
    apartment_3_bedrooms_outside_of_centre DECIMAL(10,2),
    apartment_3_bedrooms_outside_of_centre_pr VARCHAR(100),

    price_per_square_meter_to_buy_apartment_in_city_centre DECIMAL(10,2),
    price_per_square_meter_to_buy_apartment_in_city_centre_pr VARCHAR(100),
    price_per_square_meter_to_buy_apartment_outside_of_centre DECIMAL(10,2),
    price_per_square_meter_to_buy_apartment_outside_of_centre_pr VARCHAR(100),

    average_monthly_net_salary_after_tax DECIMAL(10,2),
    average_monthly_net_salary_after_tax_pr VARCHAR(50),
    mortgage_interest_rate_in_percentages__yearly__for_20_years_fixed_rate DECIMAL(5,2),
    mortgage_interest_rate_in_percentages__yearly__for_20_years_fixed_rate_pr VARCHAR(50),

    last_update VARCHAR(50)
);

